version: '3.7'
services:
  kibana:
    image: kibana:7.9.3
    container_name: kibana
    environment:
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    ports:
      - "5601:5601"
    networks:
      - es7net
  logstash:
    image: logstash:7.9.3
    container_name: logstash
    ports:
            - 5044:5044
    networks:
      - es7net
  elasticsearch:
    image: elasticsearch:7.9.3
    container_name: es7
    environment:
      - cluster.name=es7
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #jvm内存分配为512MB
      - "discovery.type=single-node" #单节点启动
      - "TZ=EST5"
    ulimits:
      nproc: 65535
      nofile:
          soft: 20000
          hard: 40000
    volumes:
      - es7data1:/usr/share/elasticsearch/data
      - es7log1:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
    networks:
      - es7net

volumes:
  es7data1:
    driver: local
  es7log1:
    driver: local
  es7logstash:
    driver: local

networks:
  es7net:
    driver: bridge
